### ISSUE TITLE
Cannot run the plugin in QGIS 3.26

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#54]
Couldn't load plugin 'OSTranslatorII' due to an error when calling its classFactory() method 

TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/OSTranslatorII/__init__.py", line 17, in classFactory
    return OsTranslatorII(iface)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/OSTranslatorII/os_translator_ii.py", line 36, in __init__
    self.dlg = OsTranslatorIIDialog(iface)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/OSTranslatorII/os_translator_ii_dialog.py", line 56, in __init__
    self.initialise_ui()
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/OSTranslatorII/os_translator_ii_dialog.py", line 206, in initialise_ui
    self.simultaneousJobsSpinBox.setValue( val )
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

Python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] 
QGIS version: 3.26.1-Buenos Aires Buenos Aires, b609df9ed4

**Comment by gregorywilliams** [comment]
The linked fix also worked for me on 3.24.3-Tisler
